### PR TITLE
Add a package.json file

### PR DESCRIPTION
**Pull request by cco3**

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by openbibleinfo** [comment]
I have a question about package-lock.json and .gitignore. They seem to reference files that aren't in the project; what do you think about excising them from this PR?

**Comment by alerque** [comment]
> I have a question about package-lock.json and .gitignore. They seem to reference files that aren't in the project; what do you think about excising them from this PR?

Both should be included. These are appropriate things to include in the project relevant to the addition of `package.json`.

**Comment by openbibleinfo** [comment]
But they're not necessary in this instance, are they? I'd rather add only needed files so as to avoid confusion in the future.

**Comment by alerque** [comment]
Necessary !== Useful.

Technically you can function without them. The lock file *should* be included to provide a known working environment that people can recreate a known-working set of dependencies. It's possible to use without, but provides functionality for use as NPM package that excluding the file wouldn't provide. It should be included.

The gitignore entry is a convenience thing, but highly recommended since the only time it will show up is in the context of a Git repository which is exactly where it's useful. It will keep the NPM cache directory.

Confusing would be bucking the norms for these ecosystems and not including things that are useful and even expected.

**Comment by cco3** [comment]
Yeah, I think @alerque summarizes it well, esp. with these being ecosystem norms.

**Comment by cco3** [comment]
Just to clarify a little, the point of a .gitignore file is to ignore files that *aren't* in the repository (i.e., its purpose is precisely to reference things not in any commits).  When someone runs `npm install`, they will create a `node_modules/`directory that should not accidentally get added to git, and this prevents that.

**Pull request merged**
